<?php

namespace App\Filament\Resources;

use App\Filament\Resources\OrderResource\Pages;
use App\Filament\Resources\OrderResource\RelationManagers;
use App\Models\Order;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\CarbonImmutable;
use Filament\Actions\Action;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Blade;

class OrderResource extends Resource
{
    protected static ?string $model = Order::class;
    protected static ?string $navigationIcon = 'fas-cart-shopping';

    protected static ?string $navigationLabel = "Orders";
    protected static ?string $modelLabel = "Order";
//    protected static ?string $navigationGroup = "Order Details";
    protected static ?string $slug = "orders";
    protected static ?int $navigationSort = 1;

    protected static ?string $recordTitleAttribute = 'customer.name';

    public static function getGlobalSearchResultTitle(Model $record): string
    {
        return $record->customer->name;
    }


    public static function getGloballySearchableAttributes(): array
    {
        return ['customer.name', 'stockItem.name', 'size.name'];
    }

    public static function getGlobalSearchResultDetails(Model $record): array
    {
        return [
            'Stock Item' => $record->stockItem->name,
            'Size' => $record->size->name,
        ]; // TODO: Change the autogenerated stub
    }

    public static function getGlobalSearchEloquentQuery(): Builder
    {
        return parent::getGlobalSearchEloquentQuery()->with('customer');
    }


    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return static::getModel()::count() < 10 ? 'warning' : 'success';
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
//                Forms\Components\TextInput::make('created_by_name')
//                    ->maxLength(255)
//                    ->default(null),
                Forms\Components\Section::make('Customer/Items Details')->schema([
                    Forms\Components\Select::make('customer_id')
                        ->relationship('customer', 'name')
                        ->searchable()
                        ->preload()
                        ->native(false)
                        ->live()
                        ->required(),
                    Forms\Components\Select::make('stock_item_id')
                        ->relationship('stockItem', 'name')
                        ->searchable()
                        ->preload()
                        ->native(false)
                        ->live()
                        ->required(),
                    Forms\Components\Select::make('size_id')
                        ->relationship('size', 'name')
                        ->searchable()
                        ->preload()
                        ->native(false)
                        ->live()
                        ->required(),
                    Forms\Components\TextInput::make('quantity')
                        ->numeric()
                        ->default(null),
                    Forms\Components\TextInput::make('each_item_amount')
                        ->label('Amount For Each Item')
                        ->numeric()
                        ->default(null)->columnSpan(1),
                    Forms\Components\TextInput::make('amount')
                        ->label('Total Amount')
                        ->numeric()
                        ->default(null),
                ])->columns(3),

                Forms\Components\Section::make('Vendor Details')->schema(
                    [
                        Forms\Components\Select::make('paper')
                            ->relationship('paperVendor', 'name')
                            ->label('Paper')
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->live()
                            ->required(),
                        Forms\Components\Select::make('plate')
                            ->relationship('plateVendor', 'name')
                            ->label('Plate')
                            ->required()
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->live()
                            ->required(),
                        Forms\Components\Select::make('printing')
                            ->relationship('printingVendor', 'name')
                            ->label('Printing')
                            ->required()
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->live()
                            ->required(),
                        Forms\Components\Select::make('lamination')
                            ->relationship('laminationVendor', 'name')
                            ->label('Lamination')
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->live()
                            ->required(),
                        Forms\Components\Select::make('binding')
                            ->relationship('bindingVendor', 'name')
                            ->label('Binding')
                            ->searchable()
                            ->preload()
                            ->native(false)
                            ->live()
                            ->required()
                            ->columnSpanFull(),

                    ]
                )->columns(2),

                Forms\Components\Section::make('Dates')->schema(
                    [
                        Forms\Components\DatePicker::make('order_date')
                            ->default(now()) // Set the default value to the current datetime
                            ->format('Y-m-d H:i:s'),
                        Forms\Components\DatePicker::make('delivery_date')
                            ->required(),
                        Forms\Components\Select::make('created_by')
                            ->relationship('user', 'name')
                            ->label('Created By')
                            ->default(Auth::user()->id)
                            ->required()
                    ])->columns(3)
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('serial_number')
                    ->label('S/N')
                    ->getStateUsing(function ($rowLoop) {
                        return $rowLoop->index + 1;
                    }),
                Tables\Columns\TextColumn::make('order_date')
                    ->date()
                    ->sortable(),
//                Tables\Columns\TextColumn::make('created_by_name')
//                    ->searchable()
//                    ->toggleable(),
                Tables\Columns\TextColumn::make('customer.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('stockItem.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('quantity')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('size.name')
                    ->sortable()
                    ->searchable(),
//                Tables\Columns\TextColumn::make('each_item_amount')
//                    ->numeric()
//                    ->sortable()
//                    ->toggleable(),
                Tables\Columns\TextColumn::make('paperVendor.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('plateVendor.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('printingVendor.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('laminationVendor.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('bindingVendor.name')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('delivery_date')
                    ->date()
                    ->sortable(),
                Tables\Columns\TextColumn::make('amount')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('user.name')
                    ->label('Created By')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                SelectFilter::make('stock_items')
                    ->multiple()
                    ->preload()
                    ->relationship('stockItem', 'name')
                    ->searchable()
                    ->label('Filter by Stock Items')
                    ->indicator('Stock Items'),
                SelectFilter::make('Customers')
                    ->multiple()
                    ->preload()
                    ->relationship('customer', 'name')
                    ->searchable()
                    ->label('Filter by Customers')
                    ->indicator('Customers'),


            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make()
                    ->successNotification(
                        Notification::make()
                            ->success()
                            ->title('Order Deleted.')
                            ->body('The Order Deleted Successfully')

                    ),
                Tables\Actions\Action::make('single_pdf')
                    ->label('PDF')
                    ->color('success')
                    ->icon('fas-download')
                    ->action(function (Model $record) {
                        return response()->streamDownload(function () use ($record) {
                            echo Pdf::loadHtml(
                                Blade::render('orderPdf', ['record' => $record])
                            )->stream();
                        }, $record->customer->name . '_' .  $record->created_at . '.pdf');
                    }),

            ])
            ->headerActions([
                Tables\Actions\Action::make('pdf')
                    ->label('PDF')
                    ->icon('fas-download')
                    ->action(function () {
                        $records = Order::all(); // Fetch all records you want to include

                        return response()->streamDownload(function () use ($records) {
                            echo Pdf::loadHtml(
                                Blade::render('ordersPdf', ['records' => $records])
                            )->stream();
                        }, 'all_orders.pdf');
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }


    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Section::make('Order info')
                    ->schema([
                        TextEntry::make('order_date')->label('Order Date'),
                        TextEntry::make('customer.name')->label('Customer'),
                        TextEntry::make('stockItem.name')->label('Stock Item'),
                        TextEntry::make('quantity')->label('Quantity'),
                        TextEntry::make('size.name')->label('Size'),
                        TextEntry::make('PaperVendor.name')->label('Paper'),
                        TextEntry::make('plateVendor.name')->label('Plate'),
                        TextEntry::make('printingVendor.name')->label('Printing'),
                        TextEntry::make('laminationVendor.name')->label('Lamination'),
                        TextEntry::make('bindingVendor.name')->label('Binding'),
                        TextEntry::make('delivery_date')->label('Delivery Date'),
                        TextEntry::make('amount')->label('Amount'),
                    ])->columns(4)
            ]);

    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListOrders::route('/'),
            'create' => Pages\CreateOrder::route('/create'),
//            'view' => Pages\ViewOrder::route('/{record}'),
            'edit' => Pages\EditOrder::route('/{record}/edit'),
        ];
    }
}
